project_id = "dfqcturrfbnzlhiaupnw"

[functions]
  [functions.accept-invitation]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
